name: MacOS shioaji

on: 
  push:
    tags:
      - "*"

jobs: 
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: set release version and set delete source code
        run: |
          echo "CI_COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "DEL_SOURCE=true" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          repository: 'Yvictor/shioaji'
          ref: ${{ env.CI_COMMIT_TAG }}
          token: ${{ secrets.SHIOAJI_GITHUB_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv wheel twine
        run: pip install pipenv==2020.6.2 wheel twine --use-feature=2020-resolver
      - name: Fixed pipenv python version 
        run: pipenv --python ${{ matrix.python-version }} 
      - name: py2pyx
        run: python py2pyx.py
      - name: Sync dev env
        run: pipenv install --dev
      - name: Sync env
        run: pipenv install
      - name: Setup build
        run: pipenv run python setup.py build_ext
      - name: Build wheel
        run: pipenv run pip wheel ./ --no-deps -w wheelhouse/
      - name: Upload wheel to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shioaji
          path: wheelhouse/shioaji*.whl
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload wheelhouse/shioaji*.whl
